- name: Install python additional packages
  yum:
    name: "{{ packages }}"
    state: present
  changed_when: true
  vars:
    packages:
      - python-pip

- name: Install python pip additional packages
  pip:
    name: "{{ pip_packages }}"
    state: present
  changed_when: true
  vars:
    pip_packages:
      - docker
      - docker-compose
