---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
#  annotations:
#    kubernetes.io/ingress.class: "gce"
spec:
  rules:
  - host: {{ .Values.ingress.hostName }}
    http:
      paths:
        - path: /
          backend:
            serviceName: {{ .Release.Name }}-{{ .Chart.Name }}
            servicePort: {{ .Values.service.externalPort }}
