---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: search-engine
    component: crawler
    release: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: search-engine
      component: crawler
      release: {{ .Release.Name }}
  template:
    metadata:
      name: crawler
      labels:
        app: search-engine
        component: crawler
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: crawler
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: crawler
          protocol: TCP
        env:
        - name: MONGO
          value: {{  .Values.db_host | default (printf "%s-mongodb" .Release.Name) }}
        - name: MONGO_PORT
          value: {{  .Values.db_port | default "27017" | quote }}
        - name: RMQ_HOST
          value: {{  .Values.rmq_host | default (printf "%s-rabbitmq" .Release.Name) }}
        - name: RMQ_QUEUE
          value: {{  .Values.rmq_queue | default "rabbitmq" | quote }}
        - name: RMQ_USERNAME
          value: {{  .Values.rmq_username | default "rabbitmq" | quote }}
        - name: RMQ_PASSWORD
          value: {{  .Values.rmq_password | default "rabbitmq" | quote }}
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
