---
apiVersion: v1
kind: Service
#name - уникальное имя ресурса, указываем релиз в метке
metadata:
  name: {{ template "crawler.fullname" . }}
  labels:
    app: search-engine
    component: crawler
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  # поды только этого релиза
  selector:
    app: search-engine
    component: crawler
    release: {{ .Release.Name }}
