---
#https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistent-volumes
#ноды требуют установленный nfs-utils
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-alertmanager
spec:
  storageClassName: prometheus-alertmanager
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - rw
    - _netdev
    - noatime
    - hard
    - nfsvers=4.1
  nfs:
    path: /srv/nfs_data/prometheus-alertmanager
    server: repo-server0
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-prometheus-alertmanager
spec:
  storageClassName: prometheus-alertmanager
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
