---
#https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistent-volumes
#ноды требуют установленный nfs-utils
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-rabbit
spec:
  #storageClassName: data-rabbit
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - rw
    - _netdev
    - noatime
    - hard
    - nfsvers=4.1
  nfs:
    path: /srv/nfs_data/rabbit
    server: repo-server0
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-data-rabbit
spec:
  #storageClassName: data-rabbit
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
