---
#https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistent-volumes
#ноды требуют установленный nfs-utils
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-rabbitmq
spec:
  storageClassName: data-rabbitmq
  capacity:
    storage: 8Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - rw
    - _netdev
    - noatime
    - hard
    - nfsvers=4.1
  nfs:
    path: /srv/nfs_data/rabbitmq
    server: repo-server0
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: pvc-data-rabbitmq
# spec:
#   storageClassName: data-rabbitmq
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 8Gi
