dependencies:
  - name: mongodb
    version: 0.4.18
    repository: file://../mongodb
  - name: rabbitmq
    version: 6.1.5
    repository: file://../rabbitmq
  - name: crawler
    version: 1.0.0
    repository: file://../crawler
  - name: search-ui
    version: 1.0.0
    repository: file://../search-ui
