- name: Create gitlab config directory
  file:
    path: "{{ gitlab_dir_config }}"
    state: directory
    mode: 0775
    recurse: yes

- name: Create gitlab logs directory
  file:
    path: "{{ gitlab_dir_logs }}"
    state: directory
    mode: 0775
    recurse: yes

- name: Create gitlab data directory
  file:
    path: "{{ gitlab_dir_data }}"
    state: directory
    mode: 0775
    recurse: yes

- name: Copy gitlab compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{ gitlab_dir_project }}/docker-compose.yml"
    mode: 0644

- name: Start GitLAB
  docker_service:
    project_src: "{{ gitlab_dir_project }}"

# - name: Install GitLab via docker-compose
#   docker_service:
#     project_name: gitlab
#     state: present
#     definition:
#       version: '2'
#       services:
#         gitlab:
#           image: gitlab/gitlab-ce:12.0.3-ce.0
#           restart: restart unless-stopped
#           log-driver: json-file --log-opt max-size=200m
#           hostname: gitlab
#           container_name: gitlab
#           environment:
#             GITLAB_OMNIBUS_CONFIG: |
#               external_url 'http://{{ inventory_hostname }}'
#               nginx['enable'] = true
#               nginx['listen_port'] = 80
#               nginx['listen_https'] = false
#               registry_external_url 'http://{{ inventory_hostname }}:9080'
#               registry['enable'] = true
#           ports:
#             - '80:80'
#             - '9080:9080'
#             - '2222:22'
#           volumes:
#             - "{{ gitlab_dir_config }}":/etc/gitlab
#             - "{{ gitlab_dir_logs }}":/var/log/gitlab
#             - "{{ gitlab_dir_data }}":/var/opt/gitlab
#   register: output

# - name: Install GitLab via docker-compose
#   debug: var=output
